//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xaimatzu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xaimatzu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\f0\fs22\lang9 Xaimatzu 2.2.0.0\par
        ///\par
        ///An artisanal screen capture utility handcrafted for fast and timely screenshots.\par
        ///\par
        ///Copyright (c) 2021 Gavin Kendall\par
        ///\par
        ///\par
        ///
        ///\pard\sa200\sl276\slmult1 This program is free software: you can redistribute it and/or modify it under the terms of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_0_About {
            get {
                return ResourceManager.GetString("help_0_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs22\lang9 Welcome\par
        ///\b0 Xaimatzu is a screen capture utility developed to take fast and timely screenshots based on the selected area of a screen and a specified filepath. A screenshot can be taken on a chosen date at a particular time or immediately taken with the Take Screenshot button or when a mouse-driven selection of an area  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_1_Welcome {
            get {
                return ResourceManager.GetString("help_1_Welcome", resourceCulture);
            }
        }
    }
}
