//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xaimatzu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xaimatzu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\f0\fs22\lang9 Xaimatzu\par
        ///{{\field{\*\fldinst{HYPERLINK https://xaimatzu.sourceforge.io/ }}{\fldrslt{https://xaimatzu.sourceforge.io/\ul0\cf0}}}}\f0\fs22\par
        ///\par
        ///An artisanal screen capture utility handcrafted for fast and timely screenshots\par
        ///\par
        ///Copyright \&apos;a9 2021 Gavin Kendall\par
        ///\par
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_0_About {
            get {
                return ResourceManager.GetString("help_0_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\f0\fs20 GNU GENERAL PUBLIC LICENSE\par
        ///Version 3, 29 June 2007\par
        ///\par
        ///Copyright \&apos;a9 2007 Free Software Foundation, Inc. &lt;{{\field{\*\fldinst{HYPERLINK &quot;https://fsf.org/&quot;}}{\fldrslt{https://fsf.org/\ul0\cf0}}}}\f0\fs20 &gt;\par
        ///\par
        ///Everyone is permitted to copy and distribute ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_1_License {
            get {
                return ResourceManager.GetString("help_1_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs22\lang9 Welcome\par
        ///\b0 Xaimatzu is a screen capture utility developed to take fast and timely screenshots based on the selected area of a screen and a specified filepath. A screenshot can be taken on a chosen date at a particular time or immediately taken with the &quot;Take Screenshot&quot; button or when a mous [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_2_Welcome {
            get {
                return ResourceManager.GetString("help_2_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs22\lang9 Command Line Options\b0\par
        ///\par
        ///You can provide command line options when running xaimatzu.exe from a command line.\par
        ///\par
        ///Specify X, Y, Width, Height, image format, and filepath:\par
        ///xaimatzu.exe -x=0 -y=0 -width=1440 -height=805 -format=jpeg -file=&quot;My Screenshot.%format%&quot;\par
        ///\par
        ///Wait for a screenshot to be take [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_3_Command_Line_Options {
            get {
                return ResourceManager.GetString("help_3_Command_Line_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap region_select {
            get {
                object obj = ResourceManager.GetObject("region_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap region_select_take_screenshot {
            get {
                object obj = ResourceManager.GetObject("region_select_take_screenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screenshot_preview {
            get {
                object obj = ResourceManager.GetObject("screenshot_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap take_screenshot {
            get {
                object obj = ResourceManager.GetObject("take_screenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
